# Generated by Django 5.1.4 on 2026-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tool', '0002_annotationlayer_signatureauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='original_filenames',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
