# Generated by Django 5.1.4 on 2026-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tool', '0003_job_ip_address_job_original_filenames_job_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True)),
                ('operation', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('original_filenames', models.TextField(blank=True)),
                ('input_files', models.JSONField(blank=True, default=list)),
                ('output_sha256', models.CharField(blank=True, max_length=64)),
                ('output_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('job_created_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
