# Generated by Django 6.0.7 on 2026-07-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tool', '0004_jobauditrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='jobauditrecord',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
