# Generated by Django 6.0.7 on 2026-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tool', '0005_job_mac_address_jobauditrecord_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='operation',
            field=models.CharField(choices=[('merge', 'Merge PDF'), ('split', 'Split PDF'), ('delete_pages', 'Delete Pages'), ('reorder_pages', 'Reorder Pages'), ('crop', 'Crop PDF'), ('compress', 'Compress PDF'), ('ocr', 'OCR PDF'), ('pdf_to_word', 'PDF to Word'), ('word_to_pdf', 'Word to PDF'), ('pdf_to_excel', 'PDF to Excel'), ('excel_to_pdf', 'Excel to PDF'), ('pdf_to_powerpoint', 'PDF to PowerPoint'), ('powerpoint_to_pdf', 'PowerPoint to PDF'), ('html_to_pdf', 'HTML to PDF'), ('pdf_to_images', 'PDF to JPG'), ('images_to_pdf', 'JPG to PDF'), ('extract_images', 'Extract Images'), ('edit', 'Edit & Sign PDF'), ('watermark', 'Watermark'), ('page_numbers', 'Page Numbers'), ('rotate', 'Rotate PDF'), ('protect', 'Protect PDF'), ('unlock', 'Unlock PDF'), ('remove_watermark', 'Remove Watermark')], max_length=64),
        ),
        migrations.AlterField(
            model_name='jobauditrecord',
            name='operation',
            field=models.CharField(choices=[('merge', 'Merge PDF'), ('split', 'Split PDF'), ('delete_pages', 'Delete Pages'), ('reorder_pages', 'Reorder Pages'), ('crop', 'Crop PDF'), ('compress', 'Compress PDF'), ('ocr', 'OCR PDF'), ('pdf_to_word', 'PDF to Word'), ('word_to_pdf', 'Word to PDF'), ('pdf_to_excel', 'PDF to Excel'), ('excel_to_pdf', 'Excel to PDF'), ('pdf_to_powerpoint', 'PDF to PowerPoint'), ('powerpoint_to_pdf', 'PowerPoint to PDF'), ('html_to_pdf', 'HTML to PDF'), ('pdf_to_images', 'PDF to JPG'), ('images_to_pdf', 'JPG to PDF'), ('extract_images', 'Extract Images'), ('edit', 'Edit & Sign PDF'), ('watermark', 'Watermark'), ('page_numbers', 'Page Numbers'), ('rotate', 'Rotate PDF'), ('protect', 'Protect PDF'), ('unlock', 'Unlock PDF'), ('remove_watermark', 'Remove Watermark')], max_length=64),
        ),
        migrations.AlterField(
            model_name='jobauditrecord',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], max_length=16),
        ),
    ]
